export { File } from './file'
export { toDataUrl } from './image/html'
export { imageBuiltIn } from './image/imageBuiltIn'
export { imageCompare } from './image/imageCompare'
export { imageInfo } from './image/imageInfo'
export { imagePixelColor } from './image/pixel'
export { magickLoaded } from './imageMagick/magickLoaded' // don't remove me - i'm important for tests
export { main } from './main/main'
export { run } from './main/run'
export * from './types'
export {registerCommandPreprocessor} from './main/executeCommandPreprocessor'